### ISSUE TITLE
Resolve "We found potential security vulnerabilities in your dependencies." warning

### ISSUE THREAD

**Issue by hammonda** [BenthamInstruments/ben-to-json#3]

**Comment by hammonda** [comment]
see https://github.com/BenthamInstruments/ben-to-json/pull/2

**Comment by richardms** [comment]
I've updated the packages used by ben-to-json. The main security issue was from 'acorn' which isn't actually used by the module, but by Jest, the test runner. Therefore there's no direct problem using the module.

**Comment by hammonda** [comment]
thanks
